<script lang="ts">
	import { onMount } from 'svelte';
	import { apiService } from '$lib/services/apiService';
	import {
		aircraft,
		setComponentModel,
		setComponentGenerating,
		setComponentError,
		type ComponentType
	} from '$lib/stores/aircraftStore';
	import type { ComponentType as CT } from '$lib/stores/aircraftStore';
	import type { AeroParameters } from '$lib/types/model';

	export let componentType: CT;

	let prompt = '';
	let previousComponentType: CT = componentType;
	let showSliders = false;

	// Parameter defaults by component type - realistic dimensions
	const defaultParams: Record<CT, AeroParameters> = {
		wings: {
			wingType: 'delta',
			span: 10,  // Realistic wing span (not 2x scaled)
			rootChord: 4,  // Wider wing chord
			tipChord: 1.5,
			sweepAngle: 30,
			thickness: 12,
			dihedral: 0,
			fuselageLength: null,
			fuselageDiameter: null,
			engineLength: null,
			engineDiameter: null,
			hasVerticalStabilizer: false,
			hasHorizontalStabilizer: false,
			positionX: 0,
			positionY: 0.5,
			positionZ: 0
		},
		fuselage: {
			wingType: 'straight',
			span: 0.8,
			rootChord: 5,  // Matches fuselage length
			tipChord: 3.5,
			sweepAngle: 0,
			thickness: 90,
			dihedral: 0,
			fuselageType: 'commercial',
			fuselageLength: 5,  // Realistic fuselage length (not 2x scaled)
			fuselageDiameter: 0.7,  // Realistic diameter (not 2x scaled)
			engineLength: null,
			engineDiameter: null,
			hasVerticalStabilizer: false,
			hasHorizontalStabilizer: false,
			positionX: 0,
			positionY: 0.5,
			positionZ: 0
		},
		tail_assembly: {
			wingType: 'swept',
			span: 5,  // Realistic tail span (not 2x scaled)
			rootChord: 2,
			tipChord: 1,
			sweepAngle: 25,
			thickness: 11,
			dihedral: 0,
			fuselageLength: null,
			fuselageDiameter: null,
			engineLength: null,
			engineDiameter: null,
			hasVerticalStabilizer: true,
			hasHorizontalStabilizer: true,
			positionX: -2.5,
			positionY: 0.5,
			positionZ: 0
		},
		engines: {
			wingType: 'straight',
			span: 0.6,
			rootChord: 2,  // Matches engine length
			tipChord: 2,
			sweepAngle: 0,
			thickness: 90,
			dihedral: 0,
			fuselageLength: null,  // MODULAR: Engines don't use fuselage parameters
			fuselageDiameter: null,
			engineLength: 2.0,  // MODULAR: Engines use their own parameters
			engineDiameter: 0.5,
			hasVerticalStabilizer: false,
			hasHorizontalStabilizer: false,
			positionX: 0,
			positionY: 0,
			positionZ: 3
		}
	};

	let parameters: AeroParameters = { ...defaultParams[componentType] };
	let lastModelId: string | null = null;

	// Reset parameters when component type changes
	$: if (componentType !== previousComponentType) {
		prompt = '';
		parameters = { ...defaultParams[componentType] };
		showSliders = false;
		lastModelId = null;
		previousComponentType = componentType;

		// Auto-generate default component when switching to a new component type
		if (!$aircraft[componentType]?.model) {
			autoGenerateDefault();
		}
	}

	// Update parameters from generated model only when model changes (not continuously)
	$: if ($aircraft[componentType]?.model?.id && $aircraft[componentType].model.id !== lastModelId) {
		parameters = { ...$aircraft[componentType].model.parameters };
		lastModelId = $aircraft[componentType].model.id;
	}

	$: component = $aircraft[componentType];
	$: isGenerating = component?.isGenerating || false;
	$: error = component?.error || null;
	$: model = component?.model || null;

	async function autoGenerateDefault() {
		console.log('Auto-generating default component:', componentType);
		setComponentGenerating(componentType, true);

		const response = await apiService.updateParameters(parameters);

		if (response.success && response.model) {
			console.log('Default component generated:', response.model.name);
			setComponentModel(componentType, response.model);
		} else {
			console.error('Auto-generation failed:', response.error);
			setComponentError(componentType, response.error || 'Failed to generate default');
		}
	}

	const componentPrompts: Record<CT, string[]> = {
		wings: [
			'Delta wing with 45° sweep, 10m span, 3m root chord',
			'Straight wing, 12m span, 2.5m chord, rectangular',
			'Swept wing with 30° sweep, 11m span, 2m root chord'
		],
		fuselage: [
			'Cylindrical fuselage, 5m length, 1.2m diameter',
			'Tapered fuselage, 6m length, streamlined',
			'Wide body fuselage, 8m length, 2m diameter'
		],
		tail_assembly: [
			'Swept tail assembly, 5m span with vertical stabilizer',
			'T-tail configuration, 4.5m horizontal span',
			'Conventional tail with rudder and elevator, 5.5m span'
		],
		engines: [
			'Twin jet engines, 1.5m length, 0.8m diameter each',
			'Single turboprop engine, 2m length, 1m diameter',
			'Four turbofan engines, 1.2m length each'
		]
	};

	async function handleGenerate() {
		if (!prompt.trim()) return;

		console.log('Generating component:', componentType, 'with prompt:', prompt);
		setComponentGenerating(componentType, true);

		// Prepend component type to prompt for better AI understanding
		const componentName = componentType.replace('_', ' ');
		const enhancedPrompt = `Generate aircraft ${componentName}: ${prompt}`;

		const response = await apiService.generateFromText(enhancedPrompt);

		if (response.success && response.model) {
			console.log('Generated successfully:', response.model.name);
			setComponentModel(componentType, response.model);
			showSliders = true; // Show sliders after generation
		} else {
			console.error('Generation failed:', response.error);
			setComponentError(componentType, response.error || 'Failed to generate');
		}
	}

	async function handleUpdateParameters() {
		console.log('Updating parameters:', parameters);
		setComponentGenerating(componentType, true);

		const response = await apiService.updateParameters(parameters);

		if (response.success && response.model) {
			console.log('Parameters updated successfully:', response.model.name);
			setComponentModel(componentType, response.model);
		} else {
			console.error('Update failed:', response.error);
			setComponentError(componentType, response.error || 'Failed to update');
		}
	}

	function useExample(example: string) {
		prompt = example;
	}

	function toggleSliders() {
		showSliders = !showSliders;
	}
</script>

<div class="component-editor">
	{#if error}
		<div class="error-message">
			{error}
		</div>
	{/if}

	{#if isGenerating}
		<div class="loading-section">
			<p>Generating {componentType.replace('_', ' ')}...</p>
		</div>
	{/if}

	<div class="sliders-section">
		<h3>Fine-tune Parameters</h3>

		{#if componentType === 'wings' || componentType === 'tail_assembly'}
				<div class="param-group">
					<label>
						Wing Type
						<select bind:value={parameters.wingType} on:change={handleUpdateParameters} disabled={isGenerating}>
							<option value="delta">Delta</option>
							<option value="swept">Swept</option>
							<option value="straight">Straight</option>
							<option value="tapered">Tapered</option>
						</select>
					</label>

					<label>
						Span: {parameters.span.toFixed(1)}m
						<input
							type="range"
							min="5"
							max="15"
							step="0.5"
							bind:value={parameters.span}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
						/>
					</label>

					<label>
						Root Chord: {parameters.rootChord.toFixed(1)}m
						<input
							type="range"
							min="1"
							max="5"
							step="0.2"
							bind:value={parameters.rootChord}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
						/>
					</label>

					<label>
						Tip Chord: {(parameters.tipChord || 0).toFixed(1)}m
						<input
							type="range"
							min="0.1"
							max="3"
							step="0.1"
							bind:value={parameters.tipChord}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
						/>
					</label>

					<label>
						Sweep Angle: {parameters.sweepAngle.toFixed(0)}°
						<input
							type="range"
							min="0"
							max="90"
							step="5"
							bind:value={parameters.sweepAngle}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
						/>
					</label>

					<label>
						Thickness: {parameters.thickness.toFixed(0)}%
						<input
							type="range"
							min="8"
							max="20"
							step="1"
							bind:value={parameters.thickness}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
						/>
					</label>

					<label>
						Dihedral: {parameters.dihedral.toFixed(0)}°
						<input
							type="range"
							min="-15"
							max="15"
							step="1"
							bind:value={parameters.dihedral}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
						/>
					</label>
				</div>

				{#if componentType === 'tail_assembly'}
					<div class="param-group">
						<label>
							<input
								type="checkbox"
								bind:checked={parameters.hasVerticalStabilizer}
								on:change={handleUpdateParameters}
								disabled={isGenerating}
							/>
							Vertical Stabilizer
						</label>

						<label>
							<input
								type="checkbox"
								bind:checked={parameters.hasHorizontalStabilizer}
								on:change={handleUpdateParameters}
								disabled={isGenerating}
							/>
							Horizontal Stabilizer
						</label>
					</div>
				{/if}
			{/if}

			{#if componentType === 'fuselage'}
				<div class="param-group">
					<label>
						Fuselage Type
						<select
							bind:value={parameters.fuselageType}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
						>
							<option value="commercial">Commercial</option>
							<option value="fighter">Fighter Jet</option>
							<option value="cargo">Cargo</option>
							<option value="private">Private</option>
						</select>
					</label>

					<label>
						Length: {(parameters.fuselageLength || 0).toFixed(1)}m
						<input
							type="range"
							min="4"
							max="20"
							step="0.5"
							bind:value={parameters.fuselageLength}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
						/>
					</label>

					<label>
						Diameter: {(parameters.fuselageDiameter || 0).toFixed(1)}m
						<input
							type="range"
							min="0.5"
							max="3"
							step="0.1"
							bind:value={parameters.fuselageDiameter}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
						/>
					</label>

					<label>
						Thickness: {parameters.thickness.toFixed(0)}%
						<input
							type="range"
							min="70"
							max="100"
							step="5"
							bind:value={parameters.thickness}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
						/>
					</label>
				</div>
			{/if}

			{#if componentType === 'engines'}
				<div class="param-group">
					<label>
						Length: {(parameters.engineLength || 2.0).toFixed(1)}m
						<input
							type="range"
							min="1.5"
							max="3"
							step="0.1"
							bind:value={parameters.engineLength}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
						/>
					</label>

					<label>
						Diameter: {(parameters.engineDiameter || 0.5).toFixed(1)}m
						<input
							type="range"
							min="0.3"
							max="0.8"
							step="0.05"
							bind:value={parameters.engineDiameter}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
						/>
					</label>
				</div>
			{/if}
		</div>
</div>

<style>
	.component-editor {
		display: flex;
		flex-direction: column;
		gap: 2rem;
	}

	.generate-section {
		padding: 1.5rem;
		background: #1e293b;
		border: 2px solid #334155;
		border-radius: 0.75rem;
	}

	.generate-section h3 {
		margin: 0 0 0.5rem;
		font-size: 1.125rem;
		font-weight: 600;
		color: #f1f5f9;
		text-transform: capitalize;
	}

	.hint {
		margin: 0 0 1rem;
		font-size: 0.875rem;
		color: #94a3b8;
	}

	.prompt-section {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	label {
		font-size: 0.875rem;
		font-weight: 600;
		color: #f1f5f9;
	}

	textarea {
		max-width: 700px;
		width: 100%;
		min-width: 300px;
		padding: 0.875rem;
		background: #1e293b;
		border: 2px solid #334155;
		border-radius: 0.5rem;
		color: #f1f5f9;
		font-size: 0.875rem;
		resize: both;
		font-family: inherit;
		transition: border-color 0.2s;
	}

	textarea:focus {
		outline: none;
		border-color: #3b82f6;
	}

	textarea::placeholder {
		color: #64748b;
	}

	.generate-btn {
		padding: 0.875rem 1.5rem;
		background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
		color: white;
		border: none;
		border-radius: 0.5rem;
		font-weight: 600;
		font-size: 0.875rem;
		cursor: pointer;
		transition: all 0.2s;
	}

	.generate-btn:not(:disabled):hover {
		transform: translateY(-2px);
		box-shadow: 0 8px 16px rgba(59, 130, 246, 0.3);
	}

	.generate-btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
		transform: none;
	}

	.error-message {
		padding: 0.875rem;
		background: rgba(239, 68, 68, 0.1);
		border: 2px solid #ef4444;
		border-radius: 0.5rem;
		color: #fca5a5;
		font-size: 0.875rem;
	}

	.examples-section h3 {
		font-size: 0.875rem;
		font-weight: 600;
		color: #94a3b8;
		margin: 0 0 1rem;
	}

	.examples-grid {
		display: grid;
		gap: 0.75rem;
	}

	.example-btn {
		padding: 0.875rem;
		background: #1e293b;
		border: 2px solid #334155;
		border-radius: 0.5rem;
		color: #cbd5e1;
		font-size: 0.8125rem;
		text-align: left;
		cursor: pointer;
		transition: all 0.2s;
	}

	.example-btn:not(:disabled):hover {
		border-color: #3b82f6;
		color: #f1f5f9;
		transform: translateX(4px);
	}

	.example-btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.component-info {
		padding: 1.5rem;
		background: linear-gradient(135deg, #10b981 0%, #059669 100%);
		border-radius: 0.75rem;
		color: white;
	}

	.component-info h3 {
		margin: 0;
		font-size: 1rem;
		font-weight: 600;
	}

	.component-name {
		margin: 0.5rem 0 0.25rem;
		font-size: 1.125rem;
		font-weight: 700;
	}

	.component-detail {
		margin: 0;
		font-size: 0.875rem;
		opacity: 0.9;
	}

	.toggle-sliders-btn {
		margin-top: 1rem;
		padding: 0.625rem 1rem;
		background: rgba(255, 255, 255, 0.2);
		border: 1px solid rgba(255, 255, 255, 0.3);
		border-radius: 0.375rem;
		color: white;
		font-size: 0.8125rem;
		font-weight: 500;
		cursor: pointer;
		transition: all 0.2s;
	}

	.toggle-sliders-btn:hover {
		background: rgba(255, 255, 255, 0.3);
		border-color: rgba(255, 255, 255, 0.5);
	}

	.sliders-section {
		padding: 1.5rem;
		background: #1e293b;
		border: 2px solid #334155;
		border-radius: 0.75rem;
	}

	.sliders-section h3 {
		margin: 0 0 1.25rem;
		font-size: 1rem;
		font-weight: 600;
		color: #f1f5f9;
	}

	.param-group {
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.param-group label {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
		font-size: 0.8125rem;
		font-weight: 500;
		color: #cbd5e1;
	}

	.param-group select {
		padding: 0.625rem;
		background: #0f172a;
		border: 2px solid #334155;
		border-radius: 0.375rem;
		color: #f1f5f9;
		font-size: 0.875rem;
		cursor: pointer;
		transition: border-color 0.2s;
	}

	.param-group select:focus {
		outline: none;
		border-color: #3b82f6;
	}

	.param-group input[type='range'] {
		-webkit-appearance: none;
		appearance: none;
		width: 100%;
		height: 6px;
		background: #334155;
		border-radius: 3px;
		outline: none;
		cursor: pointer;
	}

	.param-group input[type='range']::-webkit-slider-thumb {
		-webkit-appearance: none;
		appearance: none;
		width: 18px;
		height: 18px;
		background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
		border-radius: 50%;
		cursor: pointer;
		transition: transform 0.2s;
	}

	.param-group input[type='range']::-webkit-slider-thumb:hover {
		transform: scale(1.2);
	}

	.param-group input[type='range']::-moz-range-thumb {
		width: 18px;
		height: 18px;
		background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
		border: none;
		border-radius: 50%;
		cursor: pointer;
		transition: transform 0.2s;
	}

	.param-group input[type='range']::-moz-range-thumb:hover {
		transform: scale(1.2);
	}

	.param-group input[type='checkbox'] {
		width: 18px;
		height: 18px;
		margin-right: 0.5rem;
		cursor: pointer;
		accent-color: #3b82f6;
	}

	.param-group label:has(input[type='checkbox']) {
		flex-direction: row;
		align-items: center;
	}
</style>
