<script lang="ts">
	import { onMount } from 'svelte';
	import { apiService } from '$lib/services/apiService';
	import {
		aircraft,
		setComponentModel,
		setComponentGenerating,
		setComponentError,
		type ComponentType
	} from '$lib/stores/aircraftStore';
	import type { ComponentType as CT } from '$lib/stores/aircraftStore';
	import type { AeroParameters } from '$lib/types/model';

	export let componentType: CT;

	let prompt = '';
	let previousComponentType: CT = componentType;
	let showSliders = false;

	// Parameter defaults by component type - realistic dimensions
	const defaultParams: Record<CT, AeroParameters> = {
		wings: {
			wingType: 'delta',
			span: 10,
			rootChord: 4,
			tipChord: 1.5,
			sweepAngle: 30,
			thickness: 12,
			dihedral: 0,
			fuselageLength: null,
			fuselageDiameter: null,
			engineLength: null,
			engineDiameter: null,
			hasVerticalStabilizer: false,
			hasHorizontalStabilizer: false,
			positionX: 0,
			positionY: 0.5,
			positionZ: 0
		},
		fuselage: {
			wingType: 'straight',
			span: 0.8,
			rootChord: 5,
			tipChord: 3.5,
			sweepAngle: 0,
			thickness: 90,
			dihedral: 0,
			fuselageType: 'commercial',
			fuselageLength: 5,
			fuselageDiameter: 0.7,
			engineLength: null,
			engineDiameter: null,
			hasVerticalStabilizer: false,
			hasHorizontalStabilizer: false,
			positionX: 0,
			positionY: 0.5,
			positionZ: 0
		},
		engines: {
			wingType: 'straight',
			span: 0.6,
			rootChord: 2,
			tipChord: 2,
			sweepAngle: 0,
			thickness: 90,
			dihedral: 0,
			fuselageLength: null,
			fuselageDiameter: null,
			engineLength: 2.0,
			engineDiameter: 0.5,
			hasVerticalStabilizer: false,
			hasHorizontalStabilizer: false,
			positionX: 0,
			positionY: 0,
			positionZ: 3
		}
	};

	let parameters: AeroParameters = { ...defaultParams[componentType] };
	let lastModelId: string | null = null;

	// Reset parameters when component type changes
	$: if (componentType !== previousComponentType) {
		prompt = '';
		parameters = { ...defaultParams[componentType] };
		showSliders = false;
		lastModelId = null;
		previousComponentType = componentType;

		// Auto-generate default component when switching to a new component type
		if (!$aircraft[componentType]?.model) {
			autoGenerateDefault();
		}
	}

	// Update parameters from generated model only when model changes (not continuously)
	$: if ($aircraft[componentType]?.model?.id && $aircraft[componentType].model.id !== lastModelId) {
		parameters = { ...$aircraft[componentType].model.parameters };
		lastModelId = $aircraft[componentType].model.id;
	}

	$: component = $aircraft[componentType];
	$: isGenerating = component?.isGenerating || false;
	$: error = component?.error || null;
	$: model = component?.model || null;

	async function autoGenerateDefault() {
		console.log('Auto-generating default component:', componentType);
		setComponentGenerating(componentType, true);

		const response = await apiService.updateParameters(parameters);

		if (response.success && response.model) {
			console.log('Default component generated:', response.model.name);
			setComponentModel(componentType, response.model);
		} else {
			console.error('Auto-generation failed:', response.error);
			setComponentError(componentType, response.error || 'Failed to generate default');
		}
	}

	async function handleUpdateParameters() {
		console.log('Updating parameters:', parameters);
		setComponentGenerating(componentType, true);

		const response = await apiService.updateParameters(parameters);

		if (response.success && response.model) {
			console.log('Parameters updated successfully:', response.model.name);
			setComponentModel(componentType, response.model);
		} else {
			console.error('Update failed:', response.error);
			setComponentError(componentType, response.error || 'Failed to update');
		}
	}
</script>

<div class="component-editor">
	{#if error}
		<div class="error-panel">
			<svg viewBox="0 0 16 16" fill="none">
				<circle cx="8" cy="8" r="7" stroke="currentColor" stroke-width="1.5"/>
				<path d="M8 4V8M8 10.5V11" stroke="currentColor" stroke-width="2" stroke-linecap="square"/>
			</svg>
			<div class="error-content">
				<span class="error-label">ERROR</span>
				<p>{error}</p>
			</div>
		</div>
	{/if}

	{#if isGenerating}
		<div class="generating-panel">
			<div class="generating-spinner"></div>
			<div class="generating-content">
				<span class="generating-label">PROCESSING</span>
				<p>Generating {componentType.replace('_', ' ')}...</p>
			</div>
		</div>
	{/if}

	<!-- Parameter Controls -->
	<div class="controls-section">
		<div class="section-title">
			<svg viewBox="0 0 16 16" fill="none">
				<rect x="2" y="6" width="4" height="8" stroke="currentColor" stroke-width="1.5"/>
				<rect x="7" y="2" width="4" height="12" stroke="currentColor" stroke-width="1.5"/>
				<rect x="12" y="4" width="4" height="10" stroke="currentColor" stroke-width="1.5"/>
			</svg>
			<span>PARAMETER CONTROLS</span>
		</div>

		{#if componentType === 'wings'}
			<!-- Wing Configuration -->
			<div class="control-group">
				<div class="group-label">WING CONFIGURATION</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">TYPE</label>
						<span class="param-code">WT-01</span>
					</div>
					<select bind:value={parameters.wingType} on:change={handleUpdateParameters} disabled={isGenerating} class="param-select">
						<option value="delta">DELTA</option>
						<option value="swept">SWEPT</option>
						<option value="straight">STRAIGHT</option>
						<option value="tapered">TAPERED</option>
					</select>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">SPAN</label>
						<div class="param-value-display">
							<span class="value">{parameters.span.toFixed(2)}</span>
							<span class="unit">m</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="5"
							max="15"
							step="0.1"
							bind:value={parameters.span}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">5.0</span>
							<span class="mark">10.0</span>
							<span class="mark">15.0</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">ROOT CHORD</label>
						<div class="param-value-display">
							<span class="value">{parameters.rootChord.toFixed(2)}</span>
							<span class="unit">m</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="1"
							max="5"
							step="0.1"
							bind:value={parameters.rootChord}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">1.0</span>
							<span class="mark">3.0</span>
							<span class="mark">5.0</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">TIP CHORD</label>
						<div class="param-value-display">
							<span class="value">{(parameters.tipChord || 0).toFixed(2)}</span>
							<span class="unit">m</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="0.1"
							max="3"
							step="0.1"
							bind:value={parameters.tipChord}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">0.1</span>
							<span class="mark">1.5</span>
							<span class="mark">3.0</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">SWEEP ANGLE</label>
						<div class="param-value-display">
							<span class="value">{parameters.sweepAngle.toFixed(0)}</span>
							<span class="unit">deg</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="0"
							max="90"
							step="5"
							bind:value={parameters.sweepAngle}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">0</span>
							<span class="mark">45</span>
							<span class="mark">90</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">THICKNESS</label>
						<div class="param-value-display">
							<span class="value">{parameters.thickness.toFixed(0)}</span>
							<span class="unit">%</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="8"
							max="20"
							step="1"
							bind:value={parameters.thickness}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">8</span>
							<span class="mark">14</span>
							<span class="mark">20</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">DIHEDRAL</label>
						<div class="param-value-display">
							<span class="value">{parameters.dihedral.toFixed(0)}</span>
							<span class="unit">deg</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="-15"
							max="15"
							step="1"
							bind:value={parameters.dihedral}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">-15</span>
							<span class="mark">0</span>
							<span class="mark">15</span>
						</div>
					</div>
				</div>
			</div>

		{/if}

		{#if componentType === 'fuselage'}
			<div class="control-group">
				<div class="group-label">FUSELAGE CONFIGURATION</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">TYPE</label>
						<span class="param-code">FS-01</span>
					</div>
					<select
						bind:value={parameters.fuselageType}
						on:change={handleUpdateParameters}
						disabled={isGenerating}
						class="param-select"
					>
						<option value="commercial">COMMERCIAL</option>
						<option value="fighter">FIGHTER JET</option>
						<option value="cargo">CARGO</option>
						<option value="private">PRIVATE</option>
					</select>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">LENGTH</label>
						<div class="param-value-display">
							<span class="value">{(parameters.fuselageLength || 0).toFixed(2)}</span>
							<span class="unit">m</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="4"
							max="20"
							step="0.5"
							bind:value={parameters.fuselageLength}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">4.0</span>
							<span class="mark">12.0</span>
							<span class="mark">20.0</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">DIAMETER</label>
						<div class="param-value-display">
							<span class="value">{(parameters.fuselageDiameter || 0).toFixed(2)}</span>
							<span class="unit">m</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="0.5"
							max="3"
							step="0.1"
							bind:value={parameters.fuselageDiameter}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">0.5</span>
							<span class="mark">1.75</span>
							<span class="mark">3.0</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">THICKNESS</label>
						<div class="param-value-display">
							<span class="value">{parameters.thickness.toFixed(0)}</span>
							<span class="unit">%</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="70"
							max="100"
							step="5"
							bind:value={parameters.thickness}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">70</span>
							<span class="mark">85</span>
							<span class="mark">100</span>
						</div>
					</div>
				</div>
			</div>
		{/if}

		{#if componentType === 'engines'}
			<div class="control-group">
				<div class="group-label">ENGINE CONFIGURATION</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">LENGTH</label>
						<div class="param-value-display">
							<span class="value">{(parameters.engineLength || 2.0).toFixed(2)}</span>
							<span class="unit">m</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="1.5"
							max="3"
							step="0.1"
							bind:value={parameters.engineLength}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">1.5</span>
							<span class="mark">2.25</span>
							<span class="mark">3.0</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">DIAMETER</label>
						<div class="param-value-display">
							<span class="value">{(parameters.engineDiameter || 0.5).toFixed(2)}</span>
							<span class="unit">m</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="0.3"
							max="0.8"
							step="0.05"
							bind:value={parameters.engineDiameter}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">0.30</span>
							<span class="mark">0.55</span>
							<span class="mark">0.80</span>
						</div>
					</div>
				</div>
			</div>
		{/if}
	</div>
</div>

<style>
	.component-editor {
		display: flex;
		flex-direction: column;
		gap: var(--space-5);
	}

	/* ERROR PANEL */
	.error-panel {
		display: flex;
		gap: var(--space-3);
		padding: var(--space-4);
		background: rgba(239, 83, 80, 0.1);
		border: 1px solid var(--red-error);
		border-left: 3px solid var(--red-error);
	}

	.error-panel svg {
		width: 20px;
		height: 20px;
		color: var(--red-error);
		flex-shrink: 0;
	}

	.error-content {
		flex: 1;
	}

	.error-label {
		display: block;
		font-size: 0.625rem;
		font-weight: 700;
		letter-spacing: 0.1em;
		color: var(--red-error);
		margin-bottom: var(--space-1);
	}

	.error-content p {
		font-size: 0.8125rem;
		color: var(--gray-200);
		margin: 0;
		line-height: 1.4;
	}

	/* GENERATING PANEL */
	.generating-panel {
		display: flex;
		gap: var(--space-3);
		padding: var(--space-4);
		background: rgba(255, 167, 38, 0.1);
		border: 1px solid var(--amber-warning);
		border-left: 3px solid var(--amber-warning);
	}

	.generating-spinner {
		width: 20px;
		height: 20px;
		border: 2px solid var(--amber-warning);
		border-top-color: transparent;
		border-radius: 50%;
		animation: spin 0.8s linear infinite;
		flex-shrink: 0;
	}

	@keyframes spin {
		to { transform: rotate(360deg); }
	}

	.generating-content {
		flex: 1;
	}

	.generating-label {
		display: block;
		font-size: 0.625rem;
		font-weight: 700;
		letter-spacing: 0.1em;
		color: var(--amber-warning);
		margin-bottom: var(--space-1);
	}

	.generating-content p {
		font-size: 0.8125rem;
		color: var(--gray-200);
		margin: 0;
		text-transform: capitalize;
	}

	/* CONTROLS SECTION */
	.controls-section {
		display: flex;
		flex-direction: column;
		gap: var(--space-5);
	}

	.section-title {
		display: flex;
		align-items: center;
		gap: var(--space-2);
		padding-bottom: var(--space-3);
		border-bottom: 1px solid var(--border-subtle);
		font-size: 0.625rem;
		font-weight: 700;
		letter-spacing: 0.1em;
		color: var(--gray-400);
	}

	.section-title svg {
		width: 14px;
		height: 14px;
		color: var(--cyan-500);
	}

	/* CONTROL GROUP */
	.control-group {
		display: flex;
		flex-direction: column;
		gap: var(--space-4);
		padding: var(--space-4);
		background: var(--blueprint-surface);
		border: 1px solid var(--border-subtle);
	}

	.group-label {
		font-size: 0.5625rem;
		font-weight: 700;
		letter-spacing: 0.15em;
		color: var(--cyan-400);
		padding-bottom: var(--space-2);
		border-bottom: 1px solid var(--border-subtle);
	}

	/* PARAMETER CONTROLS */
	.param-control {
		display: flex;
		flex-direction: column;
		gap: var(--space-2);
	}

	.param-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	.param-label {
		font-size: 0.625rem;
		font-weight: 700;
		letter-spacing: 0.1em;
		color: var(--gray-300);
	}

	.param-code {
		font-family: var(--font-technical);
		font-size: 0.5625rem;
		font-weight: 700;
		letter-spacing: 0.05em;
		color: var(--gray-500);
	}

	.param-value-display {
		display: flex;
		align-items: baseline;
		gap: var(--space-1);
		font-family: var(--font-technical);
	}

	.param-value-display .value {
		font-size: 0.875rem;
		font-weight: 600;
		color: var(--cyan-400);
	}

	.param-value-display .unit {
		font-size: 0.625rem;
		color: var(--gray-500);
	}

	/* SELECT */
	.param-select {
		padding: var(--space-2) var(--space-3);
		background: var(--blueprint-bg);
		border: 1px solid var(--border-subtle);
		color: var(--gray-100);
		font-size: 0.75rem;
		font-weight: 600;
		cursor: pointer;
		transition: all 0.2s;
	}

	.param-select:hover:not(:disabled) {
		border-color: var(--cyan-600);
	}

	.param-select:focus {
		outline: none;
		border-color: var(--cyan-500);
		box-shadow: 0 0 10px var(--cyan-glow);
	}

	.param-select:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	/* SLIDER */
	.param-slider-container {
		display: flex;
		flex-direction: column;
		gap: var(--space-1);
	}

	.param-slider {
		-webkit-appearance: none;
		appearance: none;
		width: 100%;
		height: 4px;
		background: var(--blueprint-bg);
		border: 1px solid var(--border-subtle);
		border-radius: 2px;
		outline: none;
		cursor: pointer;
		position: relative;
	}

	.param-slider::-webkit-slider-thumb {
		-webkit-appearance: none;
		appearance: none;
		width: 16px;
		height: 16px;
		background: var(--cyan-500);
		border: 2px solid var(--blueprint-bg);
		border-radius: 2px;
		cursor: pointer;
		box-shadow: 0 0 10px var(--cyan-glow);
		transition: all 0.2s;
	}

	.param-slider::-webkit-slider-thumb:hover {
		background: var(--cyan-400);
		transform: scale(1.1);
		box-shadow: 0 0 15px var(--cyan-glow);
	}

	.param-slider::-moz-range-thumb {
		width: 16px;
		height: 16px;
		background: var(--cyan-500);
		border: 2px solid var(--blueprint-bg);
		border-radius: 2px;
		cursor: pointer;
		box-shadow: 0 0 10px var(--cyan-glow);
		transition: all 0.2s;
	}

	.param-slider::-moz-range-thumb:hover {
		background: var(--cyan-400);
		transform: scale(1.1);
		box-shadow: 0 0 15px var(--cyan-glow);
	}

	.param-slider:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.slider-marks {
		display: flex;
		justify-content: space-between;
		padding: 0 var(--space-1);
	}

	.mark {
		font-family: var(--font-technical);
		font-size: 0.5625rem;
		color: var(--gray-500);
	}

	/* CHECKBOX */
	.checkbox-control {
		display: flex;
		align-items: center;
		gap: var(--space-3);
		padding: var(--space-3);
		background: var(--blueprint-bg);
		border: 1px solid var(--border-subtle);
		cursor: pointer;
		transition: all 0.2s;
	}

	.checkbox-control:hover:not(:has(input:disabled)) {
		border-color: var(--cyan-600);
		background: rgba(3, 169, 244, 0.05);
	}

	.checkbox-control input[type='checkbox'] {
		width: 18px;
		height: 18px;
		margin: 0;
		cursor: pointer;
		accent-color: var(--cyan-500);
		flex-shrink: 0;
	}

	.checkbox-control input[type='checkbox']:disabled {
		cursor: not-allowed;
		opacity: 0.5;
	}

	.checkbox-label {
		display: flex;
		align-items: center;
		gap: var(--space-2);
		font-size: 0.6875rem;
		font-weight: 600;
		letter-spacing: 0.05em;
		color: var(--gray-300);
	}

	.check-icon {
		width: 12px;
		height: 12px;
		color: var(--cyan-500);
	}
</style>
